Fix broken gcov command
codecov/codecov-node pull request #173
Opened 2020-03-06 19:41 UTC by ptomato

The gcov command can't be generated if none of the gcov options are
given on the command line, since sanitizeVar() will throw an exception
when given 'undefined' as input. This runs sanitizeVar only if the
options are actually given.

2020-08-05 20:24 UTC, ptomato commented
Ping?

2020-09-08 21:46 UTC, thomasrockhu requested changes
👏 @ptomato thanks for this PR! However, I actually think it makes more sense to patch `sanitizeVar` to accept `undefined` [here](https://github.com/codecov/codecov-node/pull/173/files#diff-6a66219cd60d8f848159130aa118c38bL559), as these are the only instances that use it. Would you mind making that change instead unless you disagree?

2020-09-09 18:59 UTC, ptomato commented
Sure, updated, thanks for the review! Do note that I forgot what I was trying to do 6 months ago that was broken, so I wasn't able to test that it fixed my particular use case this time. It seems like this approach ought to have the same effect, though.

2020-09-09 20:42 UTC, thomasrockhu approved these changes

2020-09-09 20:42 UTC, merged